### ISSUE TITLE
How to visualize instance images ？

### ISSUE THREAD

**Issue by wuyingxiong** [weijielyu/Gaga#1]
Thanks for your work！
In the experimental results, it can be seen the visualized instance images.
Do you obtain continuous instance images after concatenation through trajectory or other methods like SIBR_viewer?

**Comment by weijielyu** [comment]
Thanks for your interest in our work!
Our rendered segmentation results are multi-view consistent, which means one instance will have the same mask label in all views. We just need to select the instance mask with the target label in all views and multiply it with the RGB image. Hope this answers your question.

**Comment by wuyingxiong** [comment]
Dear author！
I still have some questions about the visualization part.
In the project homepage, we can see some semantic videos. How to implement the visualization of semantic roaming?

**Comment by weijielyu** [comment]
Hi, sorry, but I do not completely understand your questions, so feel free to follow up.

As class-agnostic segmentation methods, SAM and EntitySeg do not produce semantic labels for masks, so our results also do not have semantic labels.

If you are referring to the videos, we adopted codes from https://github.com/VITA-Group/FSGS to render videos. Please let me know if that answers your question!
