### ISSUE TITLE
About mask corresponding gaussians

### ISSUE THREAD

**Issue by xiaoxiaoqiang9527** [weijielyu/Gaga#5]

**Comment by xiaoxiaoqiang9527** [comment]
Thanks for your great work! I read the paper and I'm a little confused about the part of Masks' corresponding Gaussians. Because Gaussians have a size, each Gaussian affects multiple pixels, so how do you make sure which mask the Gaussian is corresponding to? If a Gaussian affects the pixel portion of more than one mask, is the Gaussian attributed to both of those masks?

**Comment by weijielyu** [comment]
Hi, thanks for your interest in our work. We use the center of each Gaussian (x, y, z) to find the corresponding Gaussian of each mask. As the Gaussians here are used to provide spatial information of where the 3D object is located for each mask, the center is representative enough. Pleased let me know if you have any other questions!

**Comment by weijielyu** [comment]
This part does not need to modify diff-gaussian-rasterization. We directly use diff-gaussian-rasterization from [Gaussian Grouping](https://github.com/lkeab/gaussian-grouping).
